### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by hrqmonteiro** [andreadev-it/orgmode-multi-key#1]
Nothing happens if i press return on a .org file, or even it i set another key. Literally nothing opens.

**Comment by andreadev-it** [comment]
Hi, I'm sorry that it's not working for you. I'm using orgmode and orgmode-multi-key in the latest version and it seems to work just fine... could you please give more information?

For example:
- what version of orgmode have you installed?
- do you have other orgmode plugins installed?
- which package manager are you using?
- could you post the plugin installation code?

**Comment by andreadev-it** [comment]
Hi, I'll be closing this issue, since I haven't heard back from you. Feel free to contact me or open another issue with the necessary details to investigate further.

Have a nice day
